services:
  - type: web
    name: nazo-linebot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app -k gevent --timeout 120"
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: FIREBASE_CREDENTIALS_BASE64
        sync: false
